# Generated by Django 5.0.3 on 2024-05-24 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpx_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="nr_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
