# Generated by Django 5.0.3 on 2024-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpx_app', '0002_video_nr_likes_video_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
