# Generated by Django 5.0.3 on 2024-06-08 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_userprofile_has_picture'),
        ('gpx_app', '0003_video_city_video_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.userprofile')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpx_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('upvote_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.userprofile')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpx_app.video')),
            ],
        ),
    ]
