# Generated by Django 5.0.3 on 2024-06-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpx_app', '0006_alter_video_city_alter_video_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='', max_length=201),
        ),
    ]
