# Generated by Django 5.0.3 on 2024-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_userprofile_csrf_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_picture',
            field=models.BooleanField(default=False),
        ),
    ]
